import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/layout/header";
import MainFooter from "@/components/layout/footer";
import MainContent from "@/components/layout/content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fake Online Store",
  description: "Generated by Omid SoheilNia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col flex-1 min-h-screen justify-between">
          <MainHeader />
          <MainContent>{children}</MainContent>
          <MainFooter />
        </div>
      </body>
    </html>
  );
}
